---
# GCP Admin service account secret - used by GCP Provider
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: example-provider-gcp
type: Opaque
data:
  credentials.json: BASE64ENCODED_GCP_PROVIDER_CREDS
---
# GCP Provider with service account secret reference - used to provision cache resources
apiVersion: gcp.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: gcp-provider
spec:
  credentialsSecretRef:
    namespace: crossplane-system
    name: example-provider-gcp
    key: credentials.json
  projectID: PROJECT_ID