apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: comment-vibes-db
  namespace: openfaas-fn
spec:
  classSelector:
    matchLabels:
      app: comment-vibes
  writeConnectionSecretToRef:
    name: pgconn
  engineVersion: "11"
